version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: meriuts
      POSTGRES_PASSWORD: meriuts
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meriuts -d crypto_db"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G